version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: tutorial
      POSTGRES_DB: iam
      POSTGRES_PASSWORD: efrei
    ports:
      - 127.0.0.1:5001:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: lihao.wei23@gmail.com
      PGADMIN_DEFAULT_PASSWORD: efrei
    ports:
      - 127.0.0.1:8000:80
